/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project_Kamar_Hotel;

import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;


/**
 *
 * @author Ginanjar Putra
 */
public class A_Signup2 extends javax.swing.JFrame {

    /**
     * Creates new form A_Login3
     */
    public A_Signup2() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_signup = new javax.swing.JLabel();
        jLabel_nama_signup = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_pass = new javax.swing.JLabel();
        label_jabatan = new javax.swing.JLabel();
        label_alamat = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        txt_email = new javax.swing.JTextField();
        txt_jabatan = new javax.swing.JComboBox<>();
        txt_alamat = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel_signup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_signup.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_signup.setText("Signup");
        getContentPane().add(jLabel_signup);
        jLabel_signup.setBounds(600, 250, 100, 29);

        jLabel_nama_signup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_nama_signup.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nama_signup.setText("Nama");
        getContentPane().add(jLabel_nama_signup);
        jLabel_nama_signup.setBounds(450, 320, 86, 28);

        label_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_email.setForeground(new java.awt.Color(255, 255, 255));
        label_email.setText("Username");
        getContentPane().add(label_email);
        label_email.setBounds(450, 360, 86, 28);

        label_pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_pass.setForeground(new java.awt.Color(255, 255, 255));
        label_pass.setText("Password");
        getContentPane().add(label_pass);
        label_pass.setBounds(450, 400, 86, 28);

        label_jabatan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_jabatan.setForeground(new java.awt.Color(255, 255, 255));
        label_jabatan.setText("Jabatan");
        getContentPane().add(label_jabatan);
        label_jabatan.setBounds(450, 440, 86, 28);

        label_alamat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_alamat.setForeground(new java.awt.Color(255, 255, 255));
        label_alamat.setText("Alamat");
        getContentPane().add(label_alamat);
        label_alamat.setBounds(450, 480, 86, 28);

        txt_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_nama);
        txt_nama.setBounds(550, 320, 300, 28);

        txt_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_pass);
        txt_pass.setBounds(550, 400, 300, 28);

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email);
        txt_email.setBounds(550, 360, 300, 28);

        txt_jabatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jabatan", "Manajer", "Resepsionis 1", "Resepsionis 2", "Resepsionis 3", "Resepsionis 4" }));
        getContentPane().add(txt_jabatan);
        txt_jabatan.setBounds(550, 440, 300, 28);

        txt_alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_alamat);
        txt_alamat.setBounds(550, 480, 300, 28);

        btn_signup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_signup.setText("SignUp");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup);
        btn_signup.setBounds(550, 540, 100, 25);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 540, 100, 25);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("HOTEL SANTIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 10, 290, 90);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sign Up.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1284, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
       if (txt_email.getText().equals("") || txt_nama.getText().equals("") || txt_pass.getText().equals("") || txt_alamat.getText().equals("") ){
            JOptionPane.showMessageDialog(rootPane, "Harap dilengkapi");
        }
        else{
        try{
            
            String sql = "INSERT INTO singup(Name, Username, Password, Jabatan, Alamat) VALUES (" + "'" + txt_nama.getText() 
            + "','" + txt_email.getText() + "','" + txt_pass.getText() + "','" + txt_jabatan.getSelectedItem() + "','" + txt_alamat.getText() + "')";
            java.sql.Connection conn=(java.sql.Connection)Project_Kamar_Hotel.Koneksi.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            
            this.dispose();
            B_Login2 a = new B_Login2();
            a.setVisible(true);
             

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
            }
    }//GEN-LAST:event_btn_signupActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        B_Login2 a = new B_Login2();
        a.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_Signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_Signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_Signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_Signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_Signup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btn_signup;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_nama_signup;
    private javax.swing.JLabel jLabel_signup;
    private javax.swing.JLabel label_alamat;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_jabatan;
    private javax.swing.JLabel label_pass;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JComboBox<String> txt_jabatan;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
