/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project_Kamar_Hotel;

//import coba.D_Kelola_Kamar;
import javax.swing.JFrame;

/**
 *
 * @author Ginanjar Putra
 */
public class C_Menu extends javax.swing.JFrame {

    /**
     * Creates new form C_Menu
     */
    public C_Menu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_KelolaKamar = new javax.swing.JButton();
        jButton_CekIn = new javax.swing.JButton();
        jButton_CekOut = new javax.swing.JButton();
        jButton_DataPelanggan = new javax.swing.JButton();
        jButton_LogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton_KelolaKamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_KelolaKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/003-room-key.png"))); // NOI18N
        jButton_KelolaKamar.setText("  Kelola Kamar        ");
        jButton_KelolaKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KelolaKamarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_KelolaKamar);
        jButton_KelolaKamar.setBounds(400, 240, 220, 50);

        jButton_CekIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_CekIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/001-availability.png"))); // NOI18N
        jButton_CekIn.setText("  Cek In                     ");
        jButton_CekIn.setMaximumSize(new java.awt.Dimension(217, 56));
        jButton_CekIn.setMinimumSize(new java.awt.Dimension(217, 56));
        jButton_CekIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CekInActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CekIn);
        jButton_CekIn.setBounds(690, 240, 220, 50);

        jButton_CekOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_CekOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/002-overbooked.png"))); // NOI18N
        jButton_CekOut.setText("   Cek Out                  ");
        jButton_CekOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CekOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CekOut);
        jButton_CekOut.setBounds(690, 330, 220, 50);

        jButton_DataPelanggan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_DataPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006-booking.png"))); // NOI18N
        jButton_DataPelanggan.setText("  Data Pelanggan");
        jButton_DataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DataPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_DataPelanggan);
        jButton_DataPelanggan.setBounds(400, 330, 220, 50);

        jButton_LogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/005-walk.png"))); // NOI18N
        jButton_LogOut.setText("   Logout                  ");
        jButton_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_LogOut);
        jButton_LogOut.setBounds(540, 420, 220, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(620, 150, 80, 50);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menu.png"))); // NOI18N
        BG.setToolTipText("");
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1284, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_KelolaKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KelolaKamarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        D_KelolaKamar a = new D_KelolaKamar();
        a.setVisible(true);
    }//GEN-LAST:event_jButton_KelolaKamarActionPerformed

    private void jButton_CekInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CekInActionPerformed
        // TODO add your handling code here:
        this.dispose();
        E_Cek_In_Pelanggan a = new E_Cek_In_Pelanggan();
        a.setVisible(true);     
    }//GEN-LAST:event_jButton_CekInActionPerformed

    private void jButton_CekOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CekOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        F_Cek_Out_Pelanggan a = new F_Cek_Out_Pelanggan();
        a.setVisible(true);
    }//GEN-LAST:event_jButton_CekOutActionPerformed

    private void jButton_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        B_Login2 lgn = new B_Login2();
        lgn.setVisible(true);
    }//GEN-LAST:event_jButton_LogOutActionPerformed

    private void jButton_DataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DataPelangganActionPerformed
        // TODO add your handling code here:
        this.dispose();
        G_Detail_DataPelanggan d = new G_Detail_DataPelanggan();
        d.setVisible(true);
    }//GEN-LAST:event_jButton_DataPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton jButton_CekIn;
    private javax.swing.JButton jButton_CekOut;
    private javax.swing.JButton jButton_DataPelanggan;
    private javax.swing.JButton jButton_KelolaKamar;
    private javax.swing.JButton jButton_LogOut;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
