/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project_Kamar_Hotel;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JTable;
import java.sql.Connection;
import java.sql.PreparedStatement;
        
/**
 *
 * @author Ginanjar Putra
 */
public class D_KelolaKamar extends javax.swing.JFrame {

    /**
     * Creates new form D_KelolaKamar
     */
    public D_KelolaKamar() {
        initComponents();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        tabel ();
        
    }
    
    void hapus(){
        NoKamar.setText("");
        TipeKamar.setSelectedItem("");
        HargaKamar.setText("");
        StatusKamar.setSelectedItem("");
        txt_cari.setText("");
        
    }
    
    
     void cari(){
         DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No. Kamar");
        tbl.addColumn("Tipe Kamar");
        tbl.addColumn("Harga (Rp)");
        tbl.addColumn("Status Kamar");
        
        try {
            String sql = "SELECT * FROM tb_kamar WHERE NoKamar like '%" + txt_cari.getText() + "%'";
            Connection con = (Connection) Koneksi.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
             while (rs.next()){
             tbl.addRow(new Object[]{
                rs.getString("NoKamar"),
                rs.getString("TipeKamar"),
                rs.getString("HargaKamar"),
                rs.getString("StatusKamar"),
         
            });
             tabel.setModel(tbl); 
        }
            
        } catch (Exception e) {
        }
        
    }
    
    public void tabel(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No. Kamar");
        tbl.addColumn("Tipe Kamar");
        tbl.addColumn("Harga (Rp)");
        tbl.addColumn("Status Kamar");
        
        
        try {
             Statement st = (Statement)  Koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM tb_kamar");
            
            while (rs.next()){
             tbl.addRow(new Object[]{
                rs.getString("NoKamar"),
                rs.getString("TipeKamar"),
                rs.getInt("HargaKamar"),
                rs.getString("StatusKamar"),
         
            });
             tabel.setModel(tbl); 
        }
//            JOptionPane.showMessageDialog(null, "Koneksi Database  Berhasil");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + e.getMessage());
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_KelolaKamar = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        cari = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        nokamar = new javax.swing.JLabel();
        NoKamar = new javax.swing.JTextField();
        tipekamar = new javax.swing.JLabel();
        TipeKamar = new javax.swing.JComboBox<>();
        harga = new javax.swing.JLabel();
        HargaKamar = new javax.swing.JTextField();
        status = new javax.swing.JLabel();
        StatusKamar = new javax.swing.JComboBox<>();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_tambahkamar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton_KelolaKamar.setBackground(new java.awt.Color(255, 204, 0));
        jButton_KelolaKamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_KelolaKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/003-room-key.png"))); // NOI18N
        jButton_KelolaKamar.setText("  Kelola Kamar        ");
        jButton_KelolaKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KelolaKamarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_KelolaKamar);
        jButton_KelolaKamar.setBounds(80, 160, 220, 50);

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari);
        btn_cari.setBounds(1050, 250, 72, 30);

        cari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cari.setForeground(new java.awt.Color(255, 255, 255));
        cari.setText("Cari Nomor Kamar");
        getContentPane().add(cari);
        cari.setBounds(870, 230, 160, 15);

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cari);
        txt_cari.setBounds(870, 250, 170, 28);

        nokamar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nokamar.setForeground(new java.awt.Color(255, 255, 255));
        nokamar.setText("No. Kamar");
        getContentPane().add(nokamar);
        nokamar.setBounds(870, 290, 90, 15);

        NoKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoKamarActionPerformed(evt);
            }
        });
        getContentPane().add(NoKamar);
        NoKamar.setBounds(870, 310, 260, 28);

        tipekamar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipekamar.setForeground(new java.awt.Color(255, 255, 255));
        tipekamar.setText("Tipe Kamar");
        getContentPane().add(tipekamar);
        tipekamar.setBounds(870, 350, 100, 15);

        TipeKamar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TipeKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standart Room", "Deluxe Room", "Superior Room", "Family Room", "Suite Room" }));
        getContentPane().add(TipeKamar);
        TipeKamar.setBounds(870, 370, 260, 28);

        harga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setText("Harga");
        getContentPane().add(harga);
        harga.setBounds(870, 410, 80, 15);

        HargaKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaKamarActionPerformed(evt);
            }
        });
        getContentPane().add(HargaKamar);
        HargaKamar.setBounds(870, 430, 260, 28);

        status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("Status Kamar");
        getContentPane().add(status);
        status.setBounds(870, 470, 83, 15);

        StatusKamar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        StatusKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Non Aktif" }));
        StatusKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusKamarActionPerformed(evt);
            }
        });
        getContentPane().add(StatusKamar);
        StatusKamar.setBounds(870, 490, 260, 28);

        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(920, 540, 75, 33);

        btn_hapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(1010, 540, 75, 33);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButton1.setText("  Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1120, 80, 140, 40);

        btn_tambahkamar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_tambahkamar2.setText("Tambah Kamar");
        btn_tambahkamar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahkamar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambahkamar2);
        btn_tambahkamar2.setBounds(920, 580, 170, 33);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Kamar", "Tipe Kamar", "Harga (Rp)", "Status Kamar"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 240, 727, 370);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ISI.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, -30, 1440, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_KelolaKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KelolaKamarActionPerformed
        // TODO add your handling code here:
        //        this.dispose();
        //        D_Kelola_Kamar a = new D_Kelola_Kamar();
        //        a.setVisible(true);
    }//GEN-LAST:event_jButton_KelolaKamarActionPerformed

    private void HargaKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaKamarActionPerformed

    private void StatusKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusKamarActionPerformed

    private void NoKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoKamarActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        //
         try {
            String sql = "update tb_kamar set NoKamar='" + NoKamar.getText() + "', TipeKamar= '" + TipeKamar.getSelectedItem()+ "', HargaKamar= '" + HargaKamar.getText() + "', "
                    + "StatusKamar= '" + StatusKamar.getSelectedItem()+"' where NoKamar='" + NoKamar.getText() + "'" ; 
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Diedit");
            tabel();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Data Gagal Diedit");

        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Menghapus Data Ini ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
       if (ok==0){
        try {
            String sql = "delete from tb_kamar where NoKamar='"+NoKamar.getText()+"'";
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
            tabel();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Data Gagal Dihapus");

        }
       }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        C_Menu menu = new C_Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_tambahkamar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahkamar2ActionPerformed
        //CODE
        if (NoKamar.getText().equals("") || TipeKamar.getSelectedItem().equals("") || HargaKamar.getText().equals("") || StatusKamar.getSelectedItem().equals("") ){
            JOptionPane.showMessageDialog(rootPane, "Harap Lengkapi ");
        }
        else{
        try {
            String sql = "insert INTO tb_kamar (NoKamar, TipeKamar, HargaKamar, StatusKamar) values (" + " '" +NoKamar.getText() +"','" +TipeKamar.getSelectedItem() +"','" +HargaKamar.getText() +"','" +StatusKamar.getSelectedItem() +"')";
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
            
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Ada Data Yang Salah, Gagal Disimpan");
             System.out.println(e.getMessage());
        }
        tabel();
        hapus();

        }  
    }//GEN-LAST:event_btn_tambahkamar2ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        
        
        int baris = tabel.rowAtPoint(evt.getPoint());
        String NoKamar = tabel.getValueAt(baris, 0).toString();
        this.NoKamar.setText(NoKamar);
        
        String TipeKamar = tabel.getValueAt(baris, 1).toString();
        this.TipeKamar.setSelectedItem(TipeKamar);
        
        String HargaKamar = tabel.getValueAt(baris, 2).toString();
        this.HargaKamar.setText(HargaKamar);
        
        String StatusKamar = tabel.getValueAt(baris, 3).toString();
        this.StatusKamar.setSelectedItem(StatusKamar);
        
        
    }//GEN-LAST:event_tabelMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
        
        try {
            String sql = "DELETE FORM tb_kamar WHERE NoKamar ='" +NoKamar.getText() +"'";
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Data Gagal Dihapus");
        }
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_cariActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        cari();
        hapus();
    }//GEN-LAST:event_btn_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_KelolaKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_KelolaKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_KelolaKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_KelolaKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D_KelolaKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTextField HargaKamar;
    private javax.swing.JTextField NoKamar;
    private javax.swing.JComboBox<String> StatusKamar;
    private javax.swing.JComboBox<String> TipeKamar;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambahkamar2;
    private javax.swing.JLabel cari;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_KelolaKamar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nokamar;
    private javax.swing.JLabel status;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel tipekamar;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
